### ISSUE TITLE
Typst v0.7.0 breaking change for syntree package

### ISSUE THREAD

**Issue by MalteJanz** [lynn/typst-syntree#1]
## Description
After upgrading Typst from version v0.6.0 to v0.7.0 I noticed that my syntax tree lines were all over the place.

Used Package: https://github.com/typst/packages/tree/main/packages/preview/syntree/0.1.0

I haven't figured out the exact change that caused this problem, but I suspect it might be something that changed the behavior of the `place` or `measure` functions, or the line display in PDFs in general.

## Before (v0.6.0):
![image](https://github.com/typst/typst/assets/18661391/a90eff7e-7c29-4c3f-b566-fa8ec1042d5e)

## After (v0.7.0):
![image](https://github.com/typst/typst/assets/18661391/fe47d5cc-19a2-4157-9bf6-c09b8855bab8)

## Typst code
```typst
#import "@preview/syntree:0.1.0": syntree

#figure(
  caption: [Vereinfachter Syntaxbaum zu ...],
  syntree(
    nonterminal: (font: "Linux Biolinum"),
    terminal: (fill: blue),
    "[twig_block 
        [name my_block]
        [inner_twig
          [div_tag 
            [inner_tag
              [attribute
                [name class]
                [string
                  my-block-div
                  [twig_expression additional_class]
                ]
              ]
            ]
            [children
              [text hello]
            ]
          ]
        ]
      ]"
  )
) <valid_twig_example_tree>
```

**Comment by MalteJanz** [comment]
Related issue in Typst: https://github.com/typst/typst/issues/1907
(I guess this is the right place to solve this specific issue instead of there, but there was my first attempt to provide feedback 🙈 )

The issue is maybe related to the `place` function 🤷‍♂️

**Comment by crd2333** [comment]
I've not fully understanded the code yet, but maybe I found a solution. By only adding `child_width / 2` to each x value for polygon and line, it seems right now.
<img src="https://github.com/lynn/typst-syntree/assets/113617021/4454a409-730b-4902-bc14-891a9221f8f4" width=70%>
<img src="https://github.com/lynn/typst-syntree/assets/113617021/9039e53d-9a10-4ee1-852c-643a416624ad" width=70%>
